#!/usr/bin/env bash

NIX_INSTALLER=https://releases.nixos.org/nix/nix-2.3.15/install

install_homebrew() {
  echo -e "${FONT_WHITE}## Installing Homebrew...${FONT_NEUTRAL}"

  if ! command -v brew 1>/dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

    # The single quotes are here on purpose so that the expansion
    # happens when the command is run when the shell is loaded
    # shellcheck disable=SC2016
    if [[ "$ARCHITECTURE" = "arm64" ]]; then
      echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> "$HOME/.zprofile"
      eval "$(/opt/homebrew/bin/brew shellenv)"
    else
      echo 'eval "$(/usr/local/bin/brew shellenv)"' >> "$HOME/.zprofile"
      eval "$(/usr/local/bin/brew shellenv)"
    fi
  fi

  echo "Homebrew installed."
}

install_nix() {
  echo -e "${FONT_WHITE}## Installing Nix...${FONT_NEUTRAL}"

  if ! command -v nix 1>/dev/null; then
    /bin/bash -c "$(curl -L "$NIX_INSTALLER")" --darwin-use-unencrypted-nix-store-volume
  fi

  echo "Nix installed."
}

echo -e "${FONT_WHITE}# Setting up minimal environment for development${FONT_NEUTRAL}"

install_homebrew

install_nix
