brew "mas"

cask "docker"
cask "flutter"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "microsoft-outlook"
cask "microsoft-teams"
cask "plantuml"
cask "visual-studio-code"

mas "Xcode", id: 497799835
