#!/usr/bin/env bash

set -e

PROJECT_DIR="$(basename "$PWD")"
CONTAINER_IMAGE_NAME="${CONTAINER_IMAGE_NAME:-$PROJECT_DIR}"

if [[ -n $(git status -s) ]]; then
  echo "Please commit your changes first. The commit hash is used as the image tag."
  exit 2
fi

tag="$CONTAINER_IMAGE_NAME:$GIT_COMMIT_HASH"

docker buildx build --build-arg commit_id="$GIT_COMMIT_HASH" --platform=linux/arm64 -t "$tag" .
