#!/usr/bin/env bash

set -e

configure_env() {
  apt install -y "gcc-$1-linux-gnu"

  mkdir "$HOME/.cargo"

  cat << EOF > "$HOME/.cargo/config"
[target.$2-unknown-linux-musl]
linker = $2-linux-gnu-ld
EOF
}

apt update
apt upgrade -y

rustup component add clippy rustfmt
rustup target add aarch64-unknown-linux-musl
rustup target add x86_64-unknown-linux-musl

if [ "$TARGETARCH" == "amd64" ]; then
  configure_env aarch64 aarch64
elif [ "$TARGETARCH" == "arm64" ]; then
  configure_env x86-64 x86_64
fi


