---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: main-merge
spec:
  params:
  - description: Git revision to clone
    name: revision
    type: string
  - description: Git URL to repository
    name: url
    type: string
  tasks:
  - name: clone-repository
    params:
    - name: revision
      value: $(params.revision)
    - name: url
      value: $(params.url)
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: build
  - name: build-golang-builder-image
    params:
    - name: ARCHITECTURES
      value:
      - amd64
      - arm64
    - name: COMMIT_HASH
      value: $(tasks.clone-repository.results.commit)
    - name: CONTEXT
      value: go
    - name: IMAGE
      value: problem-child/private/golang-builder
    - name: REGISTRY
      value: europe-north1-docker.pkg.dev
    runAfter:
    - clone-repository
    taskRef:
      kind: ClusterTask
      name: multi-arch-build
    workspaces:
    - name: source
      workspace: build
  - name: build-rust-builder-image
    params:
    - name: ARCHITECTURES
      value:
      - amd64
      - arm64
    - name: COMMIT_HASH
      value: $(tasks.clone-repository.results.commit)
    - name: CONTEXT
      value: rust
    - name: IMAGE
      value: problem-child/private/rust-builder
    - name: REGISTRY
      value: europe-north1-docker.pkg.dev
    runAfter:
    - clone-repository
    taskRef:
      kind: ClusterTask
      name: multi-arch-build
    workspaces:
    - name: source
      workspace: build
  workspaces:
  - name: build
