---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: main-merge
spec:
  params:
    - description: Git revision to clone
      name: revision
    - description: Git URL to repository
      name: url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: main-merge-
      spec:
        params:
          - name: revision
            value: $(tt.params.revision)
          - name: url
            value: $(tt.params.url)
        pipelineRef:
          name: main-merge
        serviceAccountName: pipeline
        workspaces:
          - name: build
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: fast
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: main-merge
spec:
  params:
    - name: revision
      value: $(body.head_commit.id)
    - name: url
      value: $(body.repository.ssh_url)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: main-merge
spec:
  bindings:
    - ref: main-merge
  template:
    ref: main-merge
  interceptors:
    - cel:
        filter: body.repository.name == 'build-tools'
    - cel:
        filter: body.ref == 'refs/heads/main'
    - github:
        eventTypes:
          - push
        secretRef:
          secretKey: token
          secretName: github-webhook
  serviceAccountName: pipeline
