---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: main-merge
spec:
  params:
  - description: Git revision to clone
    name: revision
  - description: Git URL to repository
    name: url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: main-merge-
    spec:
      params:
      - name: revision
        value: $(tt.params.revision)
      - name: url
        value: $(tt.params.url)
      pipelineRef:
        name: main-merge
      serviceAccountName: pipeline
      workspaces:
      - name: build
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: fast
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: main-merge
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)
  - name: url
    value: $(body.repository.ssh_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: main-merge
spec:
  bindings:
  - ref: main-merge
  template:
    ref: main-merge
  interceptors:
  - ref:
      name: cel
    params:
    - name: filter
      value: body.repository.name == 'build-tools' && body.ref == 'refs/heads/main'
  - ref:
      name: github
    params:
    - name: eventTypes
      value:
      - push
    - name: secretRef
      value:
        secretKey: token
        secretName: github-webhook
  serviceAccountName: pipeline
