#!/usr/bin/env bash

set -e

SCRIPT_DIR="${BASH_SOURCE%/*}"

source "$SCRIPT_DIR/common"

CONTAINER_ID="$(fetch_container_id)"
IMAGE=docker.io/flyway/flyway:8.4.2
SCHEMA_DIR="${DATABASE_SCHEMA_DIR:-$PWD/sql}"

if [ -z "$CONTAINER_ID" ]; then
  echo "Database container not found."
  exit
fi

container_ip="$(docker container inspect "$CONTAINER_ID" | jq ".[].NetworkSettings.IPAddress" -r)"
jdbc_url="jdbc:postgresql://$container_ip/"

docker run -e FLYWAY_PASSWORD="$DATABASE_PASSWORD" -e FLYWAY_URL="$jdbc_url" -e FLYWAY_USER="$DATABASE_USERNAME" -v "$SCHEMA_DIR":/flyway/sql "$IMAGE" migrate
