#!/usr/bin/env bash

set -e

SCRIPT_DIR="${BASH_SOURCE%/*}"

source "$SCRIPT_DIR/common"

CONTAINER_ID="$(fetch_container_id)"

if [ -z "$CONTAINER_ID" ]; then
  echo "Database container not found."
  exit
fi

CONTAINER_IP="$(docker container inspect "$CONTAINER_ID" | jq ".[].NetworkSettings.IPAddress" -r)"
IMAGE=docker.io/flyway/flyway:8.2.0
JDBC_URL="jdbc:postgresql://$CONTAINER_IP/"
SCHEMA_DIR="${DATABASE_SCHEMA_DIR:-$PWD/sql}"

docker run -e FLYWAY_PASSWORD="$DATABASE_PASSWORD" -e FLYWAY_URL="$JDBC_URL" -e FLYWAY_USER="$DATABASE_USERNAME" -v "$SCHEMA_DIR":/flyway/sql "$IMAGE" migrate
