#!/usr/bin/env bash

SCRIPT_DIR="${BASH_SOURCE%/*}"

source "$SCRIPT_DIR/common"

IMAGE=postgres:14.1

if [ -n "$CONTAINERS" ]; then
  echo "Database container already running."
else
  echo "Starting database container..."
  docker volume create "$DATABASE_VOLUME_NAME" > /dev/null
  docker run -d -e PGDATA=/pgdata -e POSTGRES_PASSWORD="$DATABASE_PASSWORD" -p 5432:5432 --rm -v "$DATABASE_VOLUME_NAME":/pgdata "$IMAGE" > /dev/null
fi
