#!/usr/bin/env bash

SCRIPT_DIR="${BASH_SOURCE%/*}"

source "$SCRIPT_DIR/common"

for container in $CONTAINERS; do
  if [ -n "$container" ]; then
    echo "Stopping database container..."
    docker container stop "$container" > /dev/null
  fi
done
