#!/usr/bin/env bash

set -e

SCRIPT_DIR="${BASH_SOURCE%/*}"

source "$SCRIPT_DIR/common"

for container in "$(fetch_container_id)"; do
  if [ -n "$container" ]; then
    echo "Stopping database container..."
    docker container stop "$container" > /dev/null
  fi
done
